# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    post_install:
      - "curl -fsSL https://install.julialang.org | sh -s -- --yes"
      - "ln -s /home/docs/.juliaup/bin/julia /home/docs/.asdf/bin/julia"
      - 'julia -e "using Pkg; Pkg.add(\"PyCall\"); Pkg.add(\"MultiFloats\")"'
      - pip install --no-cache-dir poetry==1.4.0
      - poetry config virtualenvs.create false
      - poetry install --with doc

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: doc/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
#    - pdf

# Optionally declare the Python requirements required to build your docs
# python:
#    install:
