name: Formatting check
on:
  pull_request:

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.5.29"
        python-version: "3.12"

    - name: Check formatting
      run: |
        uv run --only-dev black mrmustard/ tests/ --check
