name: Pre-commit

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.5.29"
        python-version: 3.11

    - name: Run pre-commit
      run: uv run --frozen --only-dev pre-commit run --all-files
