name: Tensorflow tests
on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    env:
      HYPOTHESIS_PROFILE: ci

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: 1.9.3

      - name: Install dependencies
        run: |
          python -m pip install --no-cache-dir --upgrade pip
          pip install --no-cache-dir poetry==1.8.0
          poetry config virtualenvs.create false
          poetry install --extras "ray" --with dev
          julia --project="julia_pkg" -e "using Pkg; Pkg.instantiate()"

      - name: Run tests
        run: python -m pytest tests --backend=tensorflow --cov=mrmustard --cov-report=term-missing --cov-report=xml -p no:warnings --tb=native

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
