name: Test Timings
on:
  workflow_dispatch:

jobs:
  numpy:
    name: Run Numpy Tests
    uses: ./.github/workflows/tests_numpy.yml
    secrets: inherit

  jax:
    needs: numpy
    name: Run JAX Tests
    uses: ./.github/workflows/tests_jax.yml
    secrets: inherit

  tf:
    needs: jax
    name: Run Tensorflow Tests
    uses: ./.github/workflows/tests_tensorflow.yml
    secrets: inherit
